language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.10"
  - "6"
  - "8"
branches:
  only:
    - master
    - worldlineMaster
before_install:
  - git submodule update --init --recursive
script:
  - "npm run-script cover"
  - "npm run-script lint"
